import anndata as ad

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
  'train_h5ad': 'resources_test/task_template/pancreas/train_h5ad.h5ad',
  'output': 'output.h5ad'
}
meta = {
  'name': 'my_method'
}
## VIASH END

print('Reading input files', flush=True)
train_h5ad = ad.read_h5ad(par['train_h5ad'])

print('Preprocess data', flush=True)
# ... preprocessing ...

print('Train model', flush=True)
# ... train model ...

print('Generate predictions', flush=True)
# ... generate predictions ...

print("Write output AnnData to file", flush=True)
output = ad.AnnData(
  uns={
    'dataset_id': train_h5ad.uns['dataset_id'],
    'method_id': meta['name']
  },
  layers={
    'prediction': layers_prediction
  }
)
output.write_h5ad(par['output'], compression='gzip')
