import anndata as ad

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
  'input_test': 'resources_test/task_template/pancreas/test.h5ad',
  'input_prediction': 'resources_test/task_template/pancreas/prediction.h5ad',
  'output': 'output.h5ad'
}
meta = {
  'name': 'my_metric'
}
## VIASH END

print('Reading input files', flush=True)
input_test = ad.read_h5ad(par['input_test'])
input_prediction = ad.read_h5ad(par['input_prediction'])

print('Compute metrics', flush=True)
# metric_ids and metric_values can have length > 1
# but should be of equal length
uns_metric_ids = [ 'my_metric' ]
uns_metric_values = [ 0.5 ]

print("Write output AnnData to file", flush=True)
output = ad.AnnData(
  uns={
    'dataset_id': input_prediction.uns['dataset_id'],
    'method_id': input_prediction.uns['method_id'],
    'metric_ids': uns_metric_ids,
    'metric_values': uns_metric_values
  }
)
output.write_h5ad(par['output'], compression='gzip')
