name: "logistic_regression"
namespace: "methods"
version: "build_main"
argument_groups:
- name: "Arguments"
  arguments:
  - type: "file"
    name: "--input_train"
    label: "Training data"
    summary: "The training data in h5ad format"
    info:
      format:
        type: "h5ad"
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalized counts"
          required: true
        obs:
        - type: "string"
          name: "label"
          description: "Ground truth cell type labels"
          required: true
        - type: "string"
          name: "batch"
          description: "Batch information"
          required: true
        var:
        - type: "boolean"
          name: "hvg"
          description: "Whether or not the feature is considered to be a 'highly variable\
            \ gene'"
          required: true
        - type: "double"
          name: "hvg_score"
          description: "A ranking of the features by hvg."
          required: true
        obsm:
        - type: "double"
          name: "X_pca"
          description: "The resulting PCA embedding."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
    example:
    - "resources_test/task_template/pancreas/train.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--input_test"
    label: "Test data"
    summary: "The subset of molecules used for the test dataset"
    info:
      format:
        type: "h5ad"
        layers:
        - type: "integer"
          name: "counts"
          description: "Raw counts"
          required: true
        - type: "double"
          name: "normalized"
          description: "Normalized counts"
          required: true
        obs:
        - type: "string"
          name: "batch"
          description: "Batch information"
          required: true
        var:
        - type: "boolean"
          name: "hvg"
          description: "Whether or not the feature is considered to be a 'highly variable\
            \ gene'"
          required: true
        - type: "double"
          name: "hvg_score"
          description: "A ranking of the features by hvg."
          required: true
        obsm:
        - type: "double"
          name: "X_pca"
          description: "The resulting PCA embedding."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
    example:
    - "resources_test/task_template/pancreas/test.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ";"
  - type: "file"
    name: "--output"
    label: "Predicted data"
    summary: "A predicted dataset as output by a method."
    info:
      format:
        type: "h5ad"
        obs:
        - type: "string"
          name: "label_pred"
          description: "Predicted labels for the test cells."
          required: true
        uns:
        - type: "string"
          name: "dataset_id"
          description: "A unique identifier for the dataset"
          required: true
        - type: "string"
          name: "normalization_id"
          description: "Which normalization was used"
          required: true
        - type: "string"
          name: "method_id"
          description: "A unique identifier for the method"
          required: true
    example:
    - "resources_test/task_template/pancreas/prediction.h5ad"
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ";"
resources:
- type: "python_script"
  path: "script.py"
  is_executable: true
label: "Logistic Regression"
summary: "Logistic Regression with 100-dimensional PCA coordinates estimates parameters\
  \ for multivariate classification by minimizing cross entropy loss over cell type\
  \ classes."
description: "Logistic Regression estimates parameters of a logistic function for\n\
  multivariate classification tasks. Here, we use 100-dimensional whitened PCA\ncoordinates\
  \ as independent variables, and the model minimises the cross\nentropy loss over\
  \ all cell type classes.\n"
test_resources:
- type: "python_script"
  path: "run_and_check_output.py"
  is_executable: true
- type: "python_script"
  path: "check_config.py"
  is_executable: true
- type: "file"
  path: "resources_test/task_template/pancreas"
  dest: "resources_test/task_template/pancreas"
info:
  preferred_normalization: "log_cp10k"
  type: "method"
  type_info:
    label: "Method"
    summary: "A method."
    description: "A method to predict the task effects.\n"
status: "enabled"
repositories:
- type: "github"
  name: "core"
  repo: "openproblems-bio/core"
  tag: "build/main"
  path: "viash/core"
license: "MIT"
references:
  bibtex:
  - "@book{hosmer2013applied,\n  title = {Applied logistic regression},\n  author\
    \ = {Hosmer Jr, D.W. and Lemeshow, S. and Sturdivant, R.X.},\n  year = {2013},\n\
    \  publisher = {John Wiley \\& Sons},\n  volume = {398}\n}\n"
links:
  repository: "https://github.com/scikit-learn/scikit-learn"
  docker_registry: "ghcr.io"
  documentation: "https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html"
runners:
- type: "executable"
  id: "executable"
  docker_setup_strategy: "ifneedbepullelsecachedbuild"
- type: "nextflow"
  id: "nextflow"
  directives:
    label:
    - "midtime"
    - "midmem"
    - "lowcpu"
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: false
    transcript: false
    publish: false
  config:
    labels:
      lowmem: "memory = 20.Gb"
      midmem: "memory = 50.Gb"
      highmem: "memory = 100.Gb"
      lowcpu: "cpus = 5"
      midcpu: "cpus = 15"
      highcpu: "cpus = 30"
      lowtime: "time = 1.h"
      midtime: "time = 4.h"
      hightime: "time = 8.h"
      veryhightime: "time = 24.h"
  debug: false
  container: "docker"
engines:
- type: "docker"
  id: "docker"
  image: "openproblems/base_python:1.0.0"
  namespace_separator: "/"
  setup:
  - type: "python"
    user: false
    packages:
    - "scikit-learn"
    upgrade: true
  entrypoint: []
  cmd: null
build_info:
  config: "src/methods/logistic_regression/config.vsh.yaml"
  runner: "executable"
  engine: "docker"
  output: "target/executable/methods/logistic_regression"
  executable: "target/executable/methods/logistic_regression/logistic_regression"
  viash_version: "0.9.0"
  git_commit: "8871e398f0a4a956ddcabc48aaba6be40b72ac22"
  git_remote: "https://github.com/openproblems-bio/task_template"
package_config:
  name: "task_template"
  version: "build_main"
  label: "Template"
  summary: "A one sentence summary of purpose and methodology. Used for creating an\
    \ overview tables."
  description: "Provide a clear and concise description of your task, detailing the\
    \ specific problem it aims\nto solve. Outline the input data types, the expected\
    \ output, and any assumptions or constraints.\nBe sure to explain any terminology\
    \ or concepts that are essential for understanding the task.\n\nExplain the motivation\
    \ behind your proposed task. Describe the biological or computational \nproblem\
    \ you aim to address and why it's important. Discuss the current state of research\
    \ in\nthis area and any gaps or challenges that your task could help address.\
    \ This section \nshould convince readers of the significance and relevance of\
    \ your task.\n"
  info:
    image: "The name of the image file to use for the component on the website."
    test_resources:
    - type: "s3"
      path: "s3://openproblems-data/resources_test/task_template/"
      dest: "resources_test/task_template"
    - type: "s3"
      path: "s3://openproblems-data/resources_test/common/"
      dest: "resources_test/common"
  repositories:
  - type: "github"
    name: "core"
    repo: "openproblems-bio/core"
    tag: "build/main"
    path: "viash/core"
  viash_version: "0.9.0"
  source: "src"
  target: "target"
  config_mods:
  - ".runners[.type == \"nextflow\"].config.labels := { lowmem : \"memory = 20.Gb\"\
    , midmem : \"memory = 50.Gb\", highmem : \"memory = 100.Gb\", lowcpu : \"cpus\
    \ = 5\", midcpu : \"cpus = 15\", highcpu : \"cpus = 30\", lowtime : \"time = 1.h\"\
    , midtime : \"time = 4.h\", hightime : \"time = 8.h\", veryhightime : \"time =\
    \ 24.h\" }\n"
  authors:
  - name: "John Doe"
    roles:
    - "author"
    - "maintainer"
    info:
      github: "johndoe"
      orcid: "0000-0000-0000-0000"
      email: "john@doe.me"
      twitter: "johndoe"
      linkedin: "johndoe"
  keywords:
  - "single-cell"
  - "openproblems"
  - "benchmark"
  license: "MIT"
  organization: "openproblems-bio"
  references:
    doi:
    - "10.21203/rs.3.rs-4181617/v1"
  links:
    repository: "https://github.com/openproblems-bio/task_template"
    docker_registry: "ghcr.io"
    issue_tracker: "https://github.com/openproblems-bio/task_template/issues"
