name: process_datasets
namespace: workflows

argument_groups:
  - name: Inputs
    arguments:
      - name: "--input"
        __merge__: /src/api/file_common_dataset.yaml
        required: true
        direction: input
  - name: Outputs
    arguments:
      - name: "--output_train"
        __merge__: /src/api/file_train_h5ad.yaml
        required: true
        direction: output
      - name: "--output_test"
        __merge__: /src/api/file_test_h5ad.yaml
        required: true
        direction: output
      - name: "--output_solution"
        __merge__: /src/api/file_solution.yaml
        required: true
        direction: output

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - path: /common/nextflow_helpers/helper.nf

dependencies:
  - name: schema/verify_data_structure
    repository: core
  - name: data_processors/process_dataset

runners:
  - type: nextflow
