import anndata as ad
import numpy as np

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
  'input_train': 'resources_test/task_template/cxg_mouse_pancreas_atlas/train.h5ad',
  'input_test': 'resources_test/task_template/cxg_mouse_pancreas_atlas/test.h5ad',
  'input_solution': 'resources_test/task_template/cxg_mouse_pancreas_atlas/solution.h5ad',
  'output': 'output.h5ad'
}
meta = {
  'name': 'random_labels'
}
## VIASH END

print('Reading input files', flush=True)
input_train = ad.read_h5ad(par['input_train'])
input_test = ad.read_h5ad(par['input_test'])

print('Compute label distribution', flush=True)
label_distribution = input_train.obs["label"].value_counts()
label_distribution = label_distribution / label_distribution.sum()

print('Generate predictions', flush=True)
obs_label_pred = np.random.choice(
  label_distribution.index,
  size=input_test.n_obs,
  replace=True,
  p=label_distribution
)

print("Write output AnnData to file", flush=True)
output = ad.AnnData(
  uns={
    'dataset_id': input_train.uns['dataset_id'],
    'normalization_id': input_train.uns['normalization_id'],
    'method_id': meta['name']
  },
  obs={
    'label_pred': obs_label_pred
  }
)
output.obs_names = input_test.obs_names

output.write_h5ad(par['output'], compression='gzip')
